"""
Defines all the models that will be used in each agent.
"""

DEFAULT_MODEL = "gemini-2.5-flash"

# Agents
ROOT_AGENT_MODEL = DEFAULT_MODEL

VALIDATE_INPUT_AGENT_MODEL = DEFAULT_MODEL
EXTRACT_DATA_AGENT_MODEL = DEFAULT_MODEL
REPORT_AGENT_MODEL = DEFAULT_MODEL
OUTPUT_AGENT_MODEL = DEFAULT_MODEL

RESEARCH_AGENT_MODEL = DEFAULT_MODEL
DESTIONATION_AGENT_MODEL = DEFAULT_MODEL
WHAT_TO_PACK_MODEL = DEFAULT_MODEL
VERIFY_PROBLEM_AGENT_MODEL = DEFAULT_MODEL
POI_MODEL = DEFAULT_MODEL
RESEARCH_CITY_MODEL = DEFAULT_MODEL


# Tools
SEARCH_TOOL_MODEL = DEFAULT_MODEL
